Added selections, multiselect, cross selection, context menu, keyboard navigation, bookmarks
microsoft/powerbi-visuals-heatmap pull request #129
Opened 2024-12-17 15:17 UTC by vryzhkovas

Added selections, multiselect, cross selection, context menu, keyboard navigation, bookmarks

2025-02-27 13:49 UTC, kullJul requested changes

2025-02-27 13:49 UTC, kullJul commented on src/visual.ts
> +            const heatMap: Selection<TableHeatMapDataPoint> = grid.selectAll("." + TableHeatMap.ClsCategoryX);
You can use powerbi-visuals-utils-svgutils CreateClassAndSelector("className") function and then write `TableHeatMap.ClsCategoryX.selectorName` instead of `"." + TableHeatMap.ClsCategoryX`

2025-02-27 13:49 UTC, kullJul commented on src/visual.ts
> +                    return chartData.categoryX.indexOf(d.categoryX) * (gridSizeWidth + 1) + xOffset;
It is not clear what is the purpose of `+ 1`
Maybe its better to create a variable with a descriptive name and store this value there?

2025-02-27 13:49 UTC, kullJul commented on src/visual.ts
> +                .style("stroke-width", "1px");
If this is a static style, maybe move it to style.less?

2025-02-27 13:49 UTC, kullJul commented on style/style.less
> +.svgTableHeatMap rect.bordered:focus-visible{
Please add :focus as well, to prevent default outline when clicking on the element

2025-02-27 13:49 UTC, kullJul commented on style/style.less
> +.svgTableHeatMap rect.bordered:focus-visible{
Also please keep all related styles under one group:
```
.svgTableHeatMap rect.bordered{
//...
&:focus{}
&:focus-visible{}
}
```

2025-02-27 13:49 UTC, kullJul commented on style/style.less
> +  stroke: "#252423";
stroke: #252423, without double quotes

2025-02-27 13:49 UTC, kullJul commented on src/visual.ts
>          this.svg.on('contextmenu', (event: PointerEvent, dataPoint) => {
Lets move all event handlers to a separate behavior class
Use https://github.com/microsoft/PowerBI-visuals-RadarChart/blob/dev/src/radarChartWebBehavior.ts as a reference

2025-02-27 13:49 UTC, kullJul commented on src/visual.ts
> +                const isMultiselect: boolean = (<MouseEvent>event).ctrlKey || (<MouseEvent>event).shiftKey || (<MouseEvent>event).metaKey;
this.heatMapSelection.on("click", (**event: MouseEvent**, dataPoint)
const isMultiselect: boolean = event.ctrlKey || event.shiftKey || event.metaKey;

2025-03-07 10:43 UTC, vryzhkovas commented on src/visual.ts
>          this.svg.on('contextmenu', (event: PointerEvent, dataPoint) => {
Moved to VisualWebBehavior class

2025-03-07 10:43 UTC, vryzhkovas commented on style/style.less
> +  stroke: "#252423";
removed quotes

2025-03-07 10:44 UTC, vryzhkovas commented on src/visual.ts
> +                .style("stroke-width", "1px");
changed style

2025-03-07 10:44 UTC, vryzhkovas commented on src/visual.ts
> +                    return chartData.categoryX.indexOf(d.categoryX) * (gridSizeWidth + 1) + xOffset;
added constants ConstRectWidthAdjustment and ConstRectHeightAdjustment

2025-03-07 10:45 UTC, vryzhkovas commented on src/visual.ts
> +            const heatMap: Selection<TableHeatMapDataPoint> = grid.selectAll("." + TableHeatMap.ClsCategoryX);
changed

2025-04-03 11:46 UTC, kullJul approved these changes

2025-06-09 15:03 UTC, closed without merging